### ISSUE TITLE
Portable verison

### ISSUE THREAD

**Issue by BasilMas** [MrJoachim/tso-unity-client#1]
hi!
I'm interested in a portable version of Unity client. I want to use two or more accounts simultaneously.  Do you think it is possible to implement it? Thanks for any answer!

**Comment by MrJoachim** [comment]
Hi, I have added a portable version to the release page. If you have any questions/problems let me know!

**Comment by BasilMas** [comment]
Thanks, I will test it.

Added.
It doesn't work the way I wanted it to. I have two accounts. I created 2 folders - Account1 and Account2. I try to start client in folder - Account1. Then I start it in - Account2. Then I closed both clients.
If I start client in Account1 I see login from Account2

I want to have two separate settings in each folder without re-logon each time. Is it possible?

**Comment by MrJoachim** [comment]
I released a new version. Can you check again?

**Comment by BasilMas** [comment]
I've done!
Yes, this version works the way I wanted it to. Different folders store the settings for different accounts. I'll check the playability when the unity version is fixed, and I'll let you know the results then.
Thank you very much for your hard work.

**Comment by MrJoachim** [comment]
Thanks!
