### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by Latet0theParty** [MrJoachim/tso-unity-client#2]
Hi,

Great work on the stand-alone client.

Amazing that one person can achieve more than an entire team at BB!

I see you have a .tar version of the source code.

Have you tried it on a Linux distro?

If I wanted to try it, is there anything special I need to know?

Thanks,
    Richard

**Comment by MrJoachim** [comment]
It should work. I'm going to check and add a linux and macos version.

**Comment by EnderGriefeur99** [comment]
where is the linux release ?
