### ISSUE TITLE
version 1.3 ?

### ISSUE THREAD

**Issue by wofo99** [MrJoachim/tso-unity-client#4]
Hi. Any plans to release version 1.3 including pinky-clone? I would very much appreciate :-)
kind regards
Wolfgang

**Comment by MrJoachim** [comment]
It will be released soon.

**Comment by skelgaard** [comment]
it would be great to have released now with event going on :)

**Comment by MrJoachim** [comment]
Hi,
I updated with a new version.
It works only for windows.
Next month there will be a bigger update with auto update functionality etc with other OS support.

**Comment by hiswitzend** [comment]
Hi thank you working really well, will there be a portable version release as well ?

**Comment by MrJoachim** [comment]
> Hi thank you working really well, will there be a portable version release as well ?

Yes, i added the portable versions.

**Comment by hiswitzend** [comment]
thank you

**Comment by wofo99** [comment]
works like a charm ! Great work, thx a lot
